# We created this file to store the configuration parameters to evaluate the baseline CNN model. 

# Dataset
dataset_path: Dataset/spectrograms_split

# Load model
model_path_artifact: artifacts/cnn_baseline_model_path.txt

# Image parameters
img_height: 300
img_width: 400
batch_size: 32

# Evaluation settings
epochs: 50

# Output path to save the test metrics
evaluation_output_path: artifacts/cnn_baseline_evaluation_metrics.json